### ISSUE TITLE
Consider using environment variables for sensitive information

### ISSUE THREAD

**Issue by tonydelanuez** [amcquade/fresh_script#14]
Storing config information (API keys, passwords, etc.) could be troublesome if they're just plaintext on a .ini file. Maybe environment variables would be better - use os.environ.get() to fetch them and just check if they're None.

**Comment by Ragnoroct** [comment]
I can work on this. By chance do you have any suggestions for the name of this file? `.env` is the first that comes to my mind. Also, I'm assuming that this file will be added to .gitignore

**Comment by Ragnoroct** [comment]
I like this idea of having the environment file and not version controlling it. It allows contributors to save their information for testing but not have to worry about accidentally committing it.

**Comment by amcquade** [comment]
im not opposed to the change, but the .ini files arent source controlled since they are included in the .gitignore file, what makes having them as environment variables more secure?

**Comment by Ragnoroct** [comment]
I didn't realize that they were both ignored. To be honest I don't think it makes a difference. So I'm okay for not doing it.
