### ISSUE TITLE
output track info for unverified spotify posts

### ISSUE THREAD

**Issue by amcquade** [amcquade/fresh_script#42]

**Comment by rajesh1993** [comment]
Hi! Is this issue still open? If so, I would like to work on it. Let me know what the issue exactly is.

**Comment by amcquade** [comment]
@rajesh1993 yes this is still open. if you look at the code, each track post is either a spotify track, which we can easily add and output the info, or its from soucloud or youtube. for those non-spotify tracks we dont print any of the track info, so having that would be nice if the verbose option is supplied.

**Comment by alan-llin** [comment]
is this still open?

**Comment by amcquade** [comment]
@alan-llin yes this is still open. When supplying -v and a spotify track is found, the track info is written to the output. When supplying -v and a non-spotify track is found, no track info is written to the output, this issue looks to correct that.
