### ISSUE TITLE
option to print more playlists 

### ISSUE THREAD

**Issue by amcquade** [amcquade/fresh_script#44]
The user should be able to see all of their playlists not just a handful when adding more playlists

**Comment by adamfitzgibbon** [comment]
I think the default limit was 50 playlists but that's before I filter out the playlists that the user doesn't own (the ones they follow). Should we make the request with a super high limit to avoid this problem? It might make the request take a bit longer if the user has a ton of playlists followed.

**Comment by adamfitzgibbon** [comment]
whoops, looking at the documentation again, looks like the limit is actually 20 and the max is 50. We can use the max of 50 and then use the offset parameter to let the user access more playlists. I'll look into what happens if they request more and there aren't any more

**Comment by amcquade** [comment]
@adamfitzgibbon sounds good
