### ISSUE TITLE
Fresh Script and Flask feature discussion

### ISSUE THREAD

**Issue by amcquade** [amcquade/fresh_script#49]
I want to leave this issue open for anyone to make suggestions or comment on the new flask implementation of the project.

**Comment by dtcrout** [comment]
Is there any reason why this project is limited to the hiphopheads subreddit? How about allowing the user to make a playlist based on their subreddit(s) of choice?

**Comment by amcquade** [comment]
@dtcrout  there is no real reason for the limitation on the subreddit, thats just where i was interested in pulling tracks from. i have had thoughts about opening it up to the other subreddits, but the problem is a lot of the code is written specifically for hhh posts. eventually id like to see the flask component of the project to be more of a reddit music browser. i do like the idea of using multiple subreddits for a playlist.

**Comment by slammer23** [comment]
Like the idea of this project. Didn’t clone and run the app yet. But got some feature ideas: 
a) allow the user to enter a sub and use the input to search 
b) alllow user on the tracks UI to select tracks and add to the playlist proactively. Currently the UI is used to display tracks only? 
c) extend playlist functionality to YouTube - query YouTube API and search for a music video of the track. This way you can listen to the song first. Or even create a YouTube playlist.

I could work on some of those ideas

**Comment by amcquade** [comment]
@slammer23 sound like good ideas! i think feature a) might take some serious refactoring, but would probably be worthwhile. in b), if by ui you mean the flask app, right now all it really does is grabs the first 25 hot posts in r/hhh and renders those that are tracks, so anythings fair game on that front. as for c) im not sure the best way to handle youtube links, open to any suggestions

**Comment by serdar23** [comment]
I will propose a version for a),  we see where to go from there. If that is ok for you. Short explanation below. 

My idea is to create a input form with FlaskForm on the landing page (index.html). I would integrate that input field into a bootstrap navbar. This way it will be visible on all pages + a home link. Home nav-item will jump to the index page and cleans the form. 
After submitting the form with the search button, app jumps to the tracks function and re-uses the existing functionality. One change is to read the form value and search reddit based on that value.

**Comment by serdar23** [comment]
Using the CodeHub app changed my screenname :)

**Comment by amcquade** [comment]
@serdar23 go for it! honestly down for anything, current implementation is shit lol. my only reservation is that we preserve as much original script code is as possible. the origin of this project was to be able to scrap /r/hhh, and i would like at least that much to stay the same.

**Comment by bigpythonimish** [comment]
@serdar23 I'd love to contribute to the Flask app, are you working on a separate branch for this?

**Comment by bigpythonimish** [comment]
Is the work in flask branch still going on or done with already? I would like to contribute as well.

**Comment by amcquade** [comment]
@bigpythonimish yes! work is still on going, its just happening in the master branch. i think i created that when i first started putting flask into the project, now its gone stale, so just branch off the master if youd like to contribute!
