### ISSUE TITLE
Find a favicon for flask

### ISSUE THREAD

**Issue by amcquade** [amcquade/fresh_script#51]
locate favicon from /r/hiphopheads, then well determine if we want to use that or create something else.

**Comment by maxmarzolf** [comment]
https://www.flaticon.com/free-icon/vintage-radio_1454014#term=boombox&page=1&position=8

Any idea why I couldn't get this to show? I had the file in the directory, name was right, and it was in the <head>

`<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
`

I tried the other route as well 

`import os
from flask import send_from_directory

@app.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join(app.root_path, 'static'),
                               'favicon.ico', mimetype='image/vnd.microsoft.icon')`

The project is really cool by the way, we just need suggestions for good hip-hop. Wise Intelligent, Mos Def, Nas etc.

**Comment by amcquade** [comment]
@maxmarzolf simplest way to add the favicon would be to add it to the file `templates/base.html` so its included on every page.  Thanks for the help!

**Comment by maxmarzolf** [comment]
And thank you for writing back, it was my first attempt at being constructive on open source, I'm super excited to get a response hahaha

**Comment by rblcoder** [comment]
@amcquade  Can this issue be closed?

**Comment by rblcoder** [comment]
[favicon_io.zip](https://github.com/amcquade/fresh_script/files/3551264/favicon_io.zip)
Attached are all image files generated and downloaded along with the favicon https://favicon.io/favicon-generator/  
Thank you, @amcquade

**Comment by Chirag175** [comment]
I believe the solution that I've posted resolves the problem by adding a dynamic favicon and contains all the files that are necessary.

**Comment by lemiesz** [comment]
Is this issue still open looks like it was resolved?
