### ISSUE TITLE
set up logging for flask

### ISSUE THREAD

**Issue by amcquade** [amcquade/fresh_script#52]
when the server is running, it should write its outputs to a log file. research how this is done.

**Comment by sshah98** [comment]
Is this still open?

**Comment by febg** [comment]
@sshah98 Are you still working on this issue?

**Comment by amcquade** [comment]
@febg i never received a pull request from @sshah98 so its all yours

**Comment by iiSindhuii** [comment]
@febg are you working on this?

**Comment by amcquade** [comment]
@iiSindhuii never received a PR from @febg so youre good to go as far as im concerned.

**Comment by slalbertojesus** [comment]
hey, is it still available? anyone working on this?

**Comment by shafzhr** [comment]
Is it still available?

**Comment by amcquade** [comment]
@sshah98 @slalbertojesus the issue is open and there is no PR, feel free to work on this

**Comment by sshah98** [comment]
Great, I'll try my best. Someone else can take over as well, as I am back in school!

**Comment by alexpdr** [comment]
@amcquade Hi! I implemented basic logging in PR #71, please have a look and let me know if you'd like something changed :)

**Comment by mcam10** [comment]
checking on the status of this... is this still open?

**Comment by mullera3** [comment]
is this still open? @amcquade

**Comment by amcquade** [comment]
@mullera3 not sure, you'd have to install the project to find out
