### ISSUE TITLE
`praw.Reddit` instance does not use a unique user-agent

### ISSUE THREAD

**Issue by pricebenjamin** [amcquade/fresh_script#63]
The [reddit API rules](https://github.com/reddit-archive/reddit/wiki/API) ask that the supplied user-agent string be

> unique and descriptive, including the target platform, a unique application identifier, a version string, and your username as contact information, in the following format:
`<platform>:<app ID>:<version string> (by /u/<reddit username>)`

Currently, all `fresh_script` users have the same user-agent, defined by the `createPrawConfig` function:
https://github.com/amcquade/fresh_script/blob/29a482a14638531f2177aa58d98dd6ef1e6c4870/fresh.py#L56-L60

The `createPrawConfig` function creates a [`site_name`](https://praw.readthedocs.io/en/latest/code_overview/reddit_instance.html) called `'bot1'` in a local `praw.ini` file. This `site_name` is then used to create a `praw.Reddit` instance within `main`:
https://github.com/amcquade/fresh_script/blob/29a482a14638531f2177aa58d98dd6ef1e6c4870/fresh.py#L377

One solution would be to override the `user_agent` string when creating the `praw.Reddit` instance:
```python
user_agent = ' '.join([
    "Python3:FreshScript:(commit 29a482a)",
    "(by /u/<reddit_user>)",
    "(https://github.com/amcquade/fresh_script)"
])
reddit = praw.Reddit('bot1', user_agent=user_agent)
```

A helper function to generate the user string would be useful. We would also need to store the user's reddit username in one of the configuration files (see #62).

**Comment by masihtamsoy** [comment]
Hi, want to look into this issue. Please provide me initials to get started.
