### ISSUE TITLE
add arguments section to read me 

### ISSUE THREAD

**Issue by amcquade** [amcquade/fresh_script#9]
you can now pass arguments to the script, instructions on how to use those need to go in the readme

**Comment by luizpericolo** [comment]
@amcquade 
What parameters should I add to the readme? The sort and limit parameters?
I'd like to tackle this issue.

**Comment by amcquade** [comment]
@luizpericolo running the script with arguments is a newly added feature so a small section with examples of how to use them would be nice to have. you can just add that to the PR you have open now.

**Comment by luizpericolo** [comment]
@amcquade 
Ok, will do. Can you assign this task to me? Thanks.

**Comment by amcquade** [comment]
@luizpericolo are you still working on this ?
